### ISSUE TITLE
Thêm hiển thị debug cho app

### ISSUE THREAD

**Issue by dungdd-1735** [awesome-academy/pr1909-group3#35]
Vấn đề
---
Chưa rõ luồng xử lý của app

Mong muốn
---
Thêm giao diện debug, để biết luồng chạy của app

Design
---
<img width="1180" alt="debug_rails" src="https://user-images.githubusercontent.com/47093372/80306929-49e70880-87f0-11ea-84b0-6527f855f883.png">

**Comment by thiennlinh** [comment]
@dungdd-1735  Cái này em quên mất xóa mất r :((
