### ISSUE TITLE
[Refactor code] Đặt render header trong file application

### ISSUE THREAD

**Issue by dungdd-1735** [awesome-academy/pr1909-group3#36]
Vấn đề 
---
Hiện tại lệnh <%= render 'layouts/header' %> đang đặt trong từng file view. 
-> Tốn công viết, gây thừa code.

Mong muốn
---
Vì header là phần dùng chung, cho nên hãy đặt trong file application.html.erb

**Comment by thiennlinh** [comment]
@dungdd-1735 phần này em sửa trên 2 pr mới nhất r a nhé
